### ISSUE TITLE
Export no-order resulting order

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-GUI-V2#355]
No-order is both not performant and it also becomes confusing when the no-order blocks becomes sufficiently large.

While there are ways to untangle no-order blocks, most users won't bother unless it can be done programmatically.

**Comment by MortenTobiasNielsen** [comment]
For both this and the "No-order walking" issue I feel like it isn't addressing the real issue. To be fair I have been out of the game for quite some time so I might be out of the loop, but to me it seems like the main issue users want to solve with "Keep Walking", "No Order", and "Force" is to make it easier to create builds. 

The "Ghost placing auto record" feature makes it easier, but lacks one crucial thing which means I had to use hours, sometime days, trying to optimize the ordering to squeeze every last tick out of it. Using "No Order" doesn't solve this issue as far as I know, given that it is only trying to do something instead of doing the optimal thing (constrained by the route chosen by the user). So here is what I would have wanted, maybe some of the current runners can help refine it. :)

The optimal walking route is as we have discussed a few times incredibly difficult to find, so that should be left for the user to decide. The optimal way of executing steps can though be optimized, given that there is a pretty defined order to what has most value to build, the character shouldn't stop walking, and if possible speed enhancing steps should be taken. With this in mind the logic could be something like this.

- Every time a ghost building is reachable it is added to a list of reachable entities.
- It is added if other steps are necessary to fulfill the build step e.g. add coal to a furnace, add materials for a recipe, etc. 
- The amount of ticks the building is reachable is tracked. The amount of ticks is reset if the character enters the collision of the building.
-  It is tracked when the character is stepping on belt and whether it is needed to do belt direction swap, so it can be placed as soon as it would benefit the character speed.

With this information I think it should be possible to calculate an optimal step order, which would be something like this:

1. Try to get all buildings placed without the character stopping. Place Power poles first, then place production buildings (miners, assemblers, boilers, steam engines, etc.), and then other buildings. There might be a better ordering. 
2. Add speed enhancing steps if it would lower the total amount of ticks required to create the build - place belt and/or stone path, and speed enhancing trickery like those _zaspar is using.

**Comment by TragmatiS** [comment]
on no order improvements (pasted from Discord):
Imagine we have a path P (formally, a set of position-tick pairs) through the Factorio world and a set B of things we would like to construct while walking that path. Assume we have all the items we need already for simplicity. Consider a bipartite graph G where one vertice set is P and the other one is B. Draw an edge between a building and a tick if we can construct that building in that tick (i. e. it is in range, it's not in the way of our future movements etc.). Then the question of whether we can construct every building while walking the path is a question of whether there's a perfect (perfect for B, not necessarily for the whole graph) matching of vertices in that bipartite graph. One can answer that question in polynomial time using, for example, Kuhn's (https://d-k-ivanov.github.io/docs/Algorithms/Graph%20Algorithms/Maximum%20Bipartite%20Matching%20(Kuhn's%20Algorithm)/) algorithm.

**Comment by MortenTobiasNielsen** [comment]
Interesting - that could be one way of fomulating the solution. I will though leave the implementation details to the implementer. 😅

**Comment by theis999** [comment]
Honestly, i am not going to implement such complicated solution without partial goals that are individually useful. Further, i do not see this type of solution fitting neatly into any of the tools available. A separate Factorio mod is likely a better fit.

**Comment by MortenTobiasNielsen** [comment]
Understandable. It will for sure take time to develop. It would most likely make sense to make it into a mod of its own where it is build on top of the step recorder. 

It is your time, just wanted to give my 2 cents on what I think is a broader issue with the current state of TAS development. The builder uses way too much time fiddling with tick timings instead of actual progress. Sometimes it is unavoidable, but sometimes it could surely be optimized by a support tool.

**Comment by theis999** [comment]
I have developed most of the infrastructure for this issue. So this thread will close in a few days, which means that the information that isn't strictly related to the issue should be migrated to it's own thread.
